# Generated by Django 5.0.6 on 2024-09-29 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
