# Generated by Django 5.0.6 on 2024-09-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
