# Generated by Django 5.0.6 on 2024-10-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0011_alter_founder_speech_alter_principal_speech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='mission1',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission2',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission3',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='mission4',
            field=models.TextField(max_length=200),
        ),
    ]
