# Generated by Django 5.0.6 on 2024-10-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0012_alter_about_mission1_alter_about_mission2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='image',
            field=models.ImageField(default='Lajfort-default-profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='principal',
            name='image',
            field=models.ImageField(default='Lajfort-default-profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='viceprincipal',
            name='image',
            field=models.ImageField(default='Lajfort-default-profile.png', upload_to=''),
        ),
    ]
