# Generated by Django 5.0.6 on 2024-10-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0013_alter_founder_image_alter_principal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='image',
            field=models.ImageField(default='Lajfort-profile-pics.png', upload_to=''),
        ),
    ]
