# Generated by Django 5.0.6 on 2024-10-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0014_alter_founder_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='Lajfort-default-profile.png', upload_to='')),
                ('speech', models.TextField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Founder',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.DeleteModel(
            name='VicePrincipal',
        ),
    ]
