# Generated by Django 5.0.6 on 2024-10-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0016_founder_principal_viceprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='speech',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='headteacher',
            name='speech',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='principal',
            name='speech',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='viceprincipal',
            name='speech',
            field=models.TextField(max_length=300),
        ),
    ]
