# Generated by Django 5.0.6 on 2024-11-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0019_student_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overall_score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField()),
                ('percentage', models.CharField(max_length=50)),
                ('principal_remark', models.TextField(max_length=1000)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lajfortapp.student')),
            ],
        ),
    ]
