# Generated by Django 5.0.6 on 2024-11-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lajfortapp', '0020_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='overall_score',
            name='grade',
            field=models.CharField(default='A1', max_length=50),
        ),
    ]
